spring.application.name=OdontologiaOauth2Client

# credenciales quemadas para pruebas (estas no se usaran)
spring.security.user.name=admin
spring.security.user.password=1234
spring.security.user.roles=ADMIN


# Google OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}



# URL autorizados para redireccionamiento
# http://localhost:8080/login/oauth2/code/google
