services:
  postgres:
    image: postgres:17
    container_name: odontologia-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: user-db
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: odontologiadb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  dbmate:
      image: ghcr.io/amacneil/dbmate
      volumes:
        - ./migrations:/db/migrations
      environment:
        DATABASE_URL: postgres://user-db:pass123@postgres:5432/odontologiadb?sslmode=disable
      depends_on:
        - postgres

volumes:
  postgres_data:
